In [18]:
import pandas as pd
import numpy as np

In [19]:
df=pd.read_csv(r"G:\vscode\youtube_ad_revenue_dataset.csv")

In [20]:
ds=pd.DataFrame(df)

In [21]:
ds

,video_id,date,views,likes,comments,watch_time_minutes,video_length_minutes,subscribers,category,device,country,ad_revenue_usd
0,vid_3092,2024-09-24 10:50:40.993199,9936,1221.0,320.0,26497.214184,2.862137,228086,Entertainment,TV,IN,203.178237
1,vid_3459,2024-09-22 10:50:40.993199,10017,642.0,346.0,15209.747445,23.738069,736015,Gaming,Tablet,CA,140.880508
2,vid_4784,2024-11-21 10:50:40.993199,10097,1979.0,187.0,57332.658498,26.200634,240534,Education,TV,CA,360.134008
3,vid_4078,2025-01-28 10:50:40.993199,10034,1191.0,242.0,31334.517771,11.770340,434482,Entertainment,Mobile,UK,224.638261
4,vid_3522,2025-04-28 10:50:40.993199,9889,1858.0,477.0,15665.666434,6.635854,42030,Education,Mobile,CA,165.514388
...,...,...,...,...,...,...,...,...,...,...,...,...
122395,vid_2902,2024-12-14 10:50:40.993199,9853,1673.0,147.0,42075.704885,25.490195,210818,Education,Tablet,US,280.986396
122396,vid_3890,2024-07-13 10:50:40.993199,10128,1709.0,63.0,57563.703040,16.229133,878860,Music,Desktop,UK,354.612981
122397,vid_3934,2024-06-10 10:50:40.993199,10267,700.0,NaN,27549.714659,23.822365,576756,Tech,Tablet,CA,203.643106
122398,vid_4260,2024-12-22 10:50:40.993199,10240,1616.0,106.0,56967.384382,7.753099,585138,Music,Mobile,UK,351.525811
122399,vid_1056,2024-06-25 10:50:40.993199,9931,770.0,NaN,38466.837135,27.305703,517587,Tech,TV,CA,253.842824

In [22]:
ds.head()

,video_id,date,views,likes,comments,watch_time_minutes,video_length_minutes,subscribers,category,device,country,ad_revenue_usd
0,vid_3092,2024-09-24 10:50:40.993199,9936,1221.0,320.0,26497.214184,2.862137,228086,Entertainment,TV,IN,203.178237
1,vid_3459,2024-09-22 10:50:40.993199,10017,642.0,346.0,15209.747445,23.738069,736015,Gaming,Tablet,CA,140.880508
2,vid_4784,2024-11-21 10:50:40.993199,10097,1979.0,187.0,57332.658498,26.200634,240534,Education,TV,CA,360.134008
3,vid_4078,2025-01-28 10:50:40.993199,10034,1191.0,242.0,31334.517771,11.770340,434482,Entertainment,Mobile,UK,224.638261
4,vid_3522,2025-04-28 10:50:40.993199,9889,1858.0,477.0,15665.666434,6.635854,42030,Education,Mobile,CA,165.514388

In [23]:
ds.dtypes

video_id                    str
date                        str
views                     int64
likes                   float64
comments                float64
watch_time_minutes      float64
video_length_minutes    float64
subscribers               int64
category                    str
device                      str
country                     str
ad_revenue_usd          float64
dtype: object

In [24]:
ds.isnull().sum()

video_id                   0
date                       0
views                      0
likes                   6117
comments                6112
watch_time_minutes      6105
video_length_minutes       0
subscribers                0
category                   0
device                     0
country                    0
ad_revenue_usd             0
dtype: int64

In [25]:
ds.describe()

,views,likes,comments,watch_time_minutes,video_length_minutes,subscribers,ad_revenue_usd
count,122400.000000,116283.000000,116288.000000,116295.000000,122400.000000,122400.000000,122400.000000
mean,9999.856283,1099.633618,274.396636,37543.827721,16.014165,502191.719902,252.727210
std,99.881260,519.424089,129.741739,12987.724246,8.083790,288397.470103,61.957052
min,9521.000000,195.000000,48.000000,14659.105562,2.000142,1005.000000,126.590603
25%,9933.000000,650.000000,162.000000,26366.320569,9.004695,252507.500000,199.902018
50%,10000.000000,1103.000000,274.000000,37531.990337,16.005906,503465.500000,252.749699
75%,10067.000000,1547.000000,387.000000,48777.782090,23.021260,752192.000000,305.597518
max,10468.000000,2061.000000,515.000000,61557.670089,29.999799,999997.000000,382.768254

In [26]:
df_clean = df.dropna(subset=['views'])

In [27]:
mean = ds['views'].mean()
std = ds['views'].std()

In [28]:
df['z_score'] = (ds['views'] - mean) / std

In [29]:
outliers = ds[(df['z_score'].abs() > 3)]

print(outliers)

        video_id                        date  views   likes  comments  \
502     vid_3071  2024-12-14 10:50:40.993199  10360  1466.0     361.0
627       vid_74  2024-08-30 10:50:40.993199  10304  2000.0     388.0
772     vid_4945  2024-11-21 10:50:40.993199   9669  1632.0     398.0
953     vid_1073  2025-02-08 10:50:40.993199   9698  1475.0     394.0
1229    vid_2916  2024-11-09 10:50:40.993199   9674   704.0      71.0
...          ...                         ...    ...     ...       ...
119710  vid_3013  2024-09-04 10:50:40.993199  10331  1352.0     210.0
119919  vid_1186  2024-12-03 10:50:40.993199  10353   440.0     363.0
119934   vid_690  2024-06-23 10:50:40.993199  10302   459.0     249.0
120433  vid_2550  2024-06-14 10:50:40.993199   9694   683.0       NaN
122371  vid_4699  2024-09-04 10:50:40.993199   9637   916.0     287.0

        watch_time_minutes  video_length_minutes  subscribers       category  \
502           52927.517291              7.352242        27886         Gaming
627           28831.030698             29.861329       981940          Music
772                    NaN              7.617316       383868  Entertainment
953           31287.196729              4.814729       982076      Lifestyle
1229          49249.560591             12.853055       271106          Music
...                    ...                   ...          ...            ...
119710                 NaN              4.946766       459436      Education
119919        19662.870751              2.729668       329025      Lifestyle
119934        40170.724279              6.510276       796856         Gaming
120433        51202.432810              9.031264       194387           Tech
122371        26747.464334             20.814985       656753      Education

         device country  ad_revenue_usd
502     Desktop      IN      334.909633
627          TV      IN      230.656210
772      Mobile      US      159.707096
953      Tablet      CA      230.158158
1229         TV      IN      295.914351
...         ...     ...             ...
119710   Mobile      IN      191.629012
119919       TV      AU      160.445949
119934  Desktop      CA      255.232427
120433  Desktop      IN      305.397318
122371   Mobile      DE      196.990817

[323 rows x 12 columns]

In [30]:
df.head()

,video_id,date,views,likes,comments,watch_time_minutes,video_length_minutes,subscribers,category,device,country,ad_revenue_usd,z_score
0,vid_3092,2024-09-24 10:50:40.993199,9936,1221.0,320.0,26497.214184,2.862137,228086,Entertainment,TV,IN,203.178237,-0.639322
1,vid_3459,2024-09-22 10:50:40.993199,10017,642.0,346.0,15209.747445,23.738069,736015,Gaming,Tablet,CA,140.880508,0.171641
2,vid_4784,2024-11-21 10:50:40.993199,10097,1979.0,187.0,57332.658498,26.200634,240534,Education,TV,CA,360.134008,0.972592
3,vid_4078,2025-01-28 10:50:40.993199,10034,1191.0,242.0,31334.517771,11.770340,434482,Entertainment,Mobile,UK,224.638261,0.341843
4,vid_3522,2025-04-28 10:50:40.993199,9889,1858.0,477.0,15665.666434,6.635854,42030,Education,Mobile,CA,165.514388,-1.109881

In [31]:
df.columns

Index(['video_id', 'date', 'views', 'likes', 'comments', 'watch_time_minutes',
       'video_length_minutes', 'subscribers', 'category', 'device', 'country',
       'ad_revenue_usd', 'z_score'],
      dtype='str')

In [32]:

df['likes'] = df['likes'].fillna(df['likes'].median())
df['comments'] = df['comments'].fillna(df['comments'].median())
df['watch_time_minutes'] = df['watch_time_minutes'].fillna(df['watch_time_minutes'].median())


print(df.isnull().sum())

video_id                0
date                    0
views                   0
likes                   0
comments                0
watch_time_minutes      0
video_length_minutes    0
subscribers             0
category                0
device                  0
country                 0
ad_revenue_usd          0
z_score                 0
dtype: int64

In [33]:
df['engagement_rate'] = (df['likes'] + df['comments']) / df['views']

In [34]:
df['watch_time_per_view'] = df['watch_time_minutes'] / df['views']

In [35]:
print(df[['views', 'likes', 'comments', 'engagement_rate', 'watch_time_per_view']].head())

   views   likes  comments  engagement_rate  watch_time_per_view
0   9936  1221.0     320.0         0.155093             2.666789
1  10017   642.0     346.0         0.098632             1.518393
2  10097  1979.0     187.0         0.214519             5.678187
3  10034  1191.0     242.0         0.142814             3.122834
4   9889  1858.0     477.0         0.236121             1.584151

In [36]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 122400 entries, 0 to 122399
Data columns (total 15 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   video_id              122400 non-null  str
 1   date                  122400 non-null  str
 2   views                 122400 non-null  int64
 3   likes                 122400 non-null  float64
 4   comments              122400 non-null  float64
 5   watch_time_minutes    122400 non-null  float64
 6   video_length_minutes  122400 non-null  float64
 7   subscribers           122400 non-null  int64
 8   category              122400 non-null  str
 9   device                122400 non-null  str
 10  country               122400 non-null  str
 11  ad_revenue_usd        122400 non-null  float64
 12  z_score               122400 non-null  float64
 13  engagement_rate       122400 non-null  float64
 14  watch_time_per_view   122400 non-null  float64
dtypes: float64(8), int64(2), str(5)
memory usage: 19.7 MB

In [37]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in .\Lib\site-packages (1.9.1)
Requirement already satisfied: numpy>=1.24.1 in .\Lib\site-packages (from scikit-learn) (2.5.3)
Requirement already satisfied: scipy>=1.10.0 in .\Lib\site-packages (from scikit-learn) (1.18.1)
Requirement already satisfied: joblib>=1.4.0 in .\Lib\site-packages (from scikit-learn) (1.6.0)
Requirement already satisfied: narwhals>=2.0.1 in .\Lib\site-packages (from scikit-learn) (2.27.1)
Requirement already satisfied: threadpoolctl>=3.5.0 in .\Lib\site-packages (from scikit-learn) (3.7.0)
Requirement already satisfied: cloudpickle>=3.0 in .\Lib\site-packages (from joblib>=1.4.0->scikit-learn) (3.1.2)

In [38]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.svm import SVR
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

In [39]:
features = ['views', 'likes', 'comments', 'watch_time_minutes', 'video_length_minutes', 'subscribers', 'engagement_rate']
X = df[features]
y = df['ad_revenue_usd']

In [40]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [24]:
models = {
    "Linear Regression": LinearRegression(),
    "Decision Tree": DecisionTreeRegressor(random_state=42),
    "Random Forest": RandomForestRegressor(random_state=42),
    "Gradient Boosting": GradientBoostingRegressor(random_state=42),
    "Support Vector Regressor (SVR)": SVR()
}

In [ ]:
results = []

for name, model in models.items():
    # Model Train
    model.fit(X_train, y_train)
    
    # Predictions
    y_pred = model.predict(X_test)
    
    # Metrics calculation
    mae = mean_absolute_error(y_test, y_pred)
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    r2 = r2_score(y_test, y_pred)
    
    results.append({"Model": name, "MAE": mae, "RMSE": rmse, "R2 Score": r2})


results_df = pd.DataFrame(results)
print(results_df)

                            Model        MAE       RMSE  R2 Score
0               Linear Regression   3.276927  14.091475  0.948214
1                   Decision Tree   5.292843  19.974728  0.895946
2                   Random Forest   3.692022  14.148411  0.947795
3               Gradient Boosting   3.826713  14.116165  0.948032
4  Support Vector Regressor (SVR)  16.188966  22.279042  0.870553

In [7]:
from sklearn.ensemble import RandomForestRegressor
import joblib

In [41]:
best_model = RandomForestRegressor(n_estimators=50, random_state=42, n_jobs=-1)
best_model.fit(X_train, y_train)

RandomForestRegressor(n_estimators=50, n_jobs=-1, random_state=42)

In [42]:
joblib.dump(best_model, 'youtube_model.pkl')

['youtube_model.pkl']

In [43]:
print("Success! Model successfully pickled and saved as 'youtube_model.pkl'")

Success! Model successfully pickled and saved as 'youtube_model.pkl'